// SPDX-License-Identifier: Commons-Clause-1.0
//  __  __     _        ___     _
// |  \/  |___| |_ __ _| __|_ _| |__
// | |\/| / -_)  _/ _` | _/ _` | '_ \
// |_|  |_\___|\__\__,_|_|\__,_|_.__/
//
// Launch your crypto game or gamefi project's blockchain
// infrastructure & game APIs fast with https://trymetafab.com

pragma solidity ^0.8.16;

import "@openzeppelin/contracts/token/ERC1155/IERC1155.sol";
import "../common/ISystem.sol";

interface IERC1155_Game_Items_Collection is IERC1155, ISystem  {
  // autogenerated getters
  function itemIds(uint256 index) external view returns (uint256);
  function itemBaseURI() external view returns (string memory);
  function itemExists(uint256 index) external view returns (bool);
  function itemSupplies(uint256 itemId) external view returns (uint256);
  function itemTransferTimelocks(uint256 itemId) external view returns(uint256);

  // functions
  function setItemURI(uint256 _itemId, string memory _uri) external;
  function setItemBaseURI(string memory _itemsBaseURI) external;
  function isItemTransferrable(uint256 _itemId) external view returns (bool);
  function setItemTransferTimelock(uint256 _itemId, uint256 _unlockTimestamp) external;
  function mintToAddress(address _toAddress, uint256 _itemId, uint256 _quantity) external;
  function mintBatchToAddress(address _toAddress, uint256[] calldata _itemIds, uint256[] calldata _quantities) external;
  function burnFromAddress(address _fromAddress, uint256 _itemId, uint256 _quantity) external;
  function burnBatchFromAddress(address _fromAddress, uint256[] calldata _itemIds, uint256[] calldata _quantities) external;
  function bulkSafeBatchTransferFrom(address _from, address[] calldata _toAddresses, uint256[] calldata _itemIds, uint256[] calldata _quantitiesPerAddress) external;
  function totalItemIds() external view returns (uint256);
  function allItemIds() external view returns (uint256[] memory);
  function allItemSupplies() external view returns (uint256[][] memory);
  function allItemURIs() external view returns (string[] memory);
  function balanceOfAll(address _address) external view returns(uint256[][] memory);
  function paginateItemIds(uint256 itemIdsStartIndexInclusive, uint256 limit) external view returns (uint256[] memory);
  function paginateItemSupplies(uint256 itemIdsStartIndexInclusive, uint256 limit) external view returns (uint256[][] memory);
  function paginateItemURIs(uint256 itemIdsStartIndexInclusive, uint256 limit) external view returns (string[] memory);
  function transferOwnershipControl(address _newOwner) external;
}
